[package]
name = "catan"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
futures = "0.3.34"
maud = "0.27.0"
rand = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
tokio-stream = { version = "0.1.19", features = ["sync"] }
tower-http = { version = "0.7.1", features = ["fs", "compression-gzip", "trace"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = { version = "1.27.0", features = ["v4"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

